### ISSUE TITLE
Plotting?

### ISSUE THREAD

**Issue by qmwugbt112** [wurmlab/oswitch#16]
I tried running R from biolinux.  Neither X11() nor quartz() would open a plotting window.  Is there any way round this? I'm currently trying to install X11 on the Mac

> plot(1:10,runif(10))
# no plot produced
> X11()
Error in .External2(C_X11, d$display, d$width, d$height, d$pointsize,  : 
  unable to start device X11cairo
In addition: Warning message:
In X11() : unable to open connection to X11 display ''
> quartz()
Warning message:
In quartz() : Quartz device is not available on this platform
>

**Comment by yeban** [comment]
Haven't tested / worked on display functionality from docker containers yet.

**Comment by qmwugbt112** [comment]
FYI I've installed X11 and got it working from R running on OS X, but in this case miracles don't happen - it does not work from R in biolinux.

**Comment by yeban** [comment]
I would have been surprised if opening a window on host "just worked" from docker container.

Something like this could work: `docker run -it -v $DISPLAY:$DISPLAY -e DISPLAY=$DISPLAY <image>`

**Comment by yannickwurm** [comment]
Needs to show elegant error message if X is impossible (because X11 not installed or doesn't accept export - with link to proper instructions)

**Comment by bmpvieira** [comment]
Relevant (GUIs section): https://blog.jessfraz.com/posts/docker-containers-on-the-desktop.html

**Comment by yannickwurm** [comment]
This is a "generic" issue for docker - thus I feel (hope) that docker will improve to overcome this. So we should not be investing energy redundantly. 

Furthermore, there are additional challenges (e.g. will it work on your local X if you're using docker on a machine on the cluster?).  

Finally, things like R can output to pdf rather than to X.   `pdf("output.pdf"); plot(1:10, 1:10); dev.off()`  - many of us already prefer this way of using R....

Thus I'm closing this issue for now.

**Comment by bmpvieira** [comment]
Just for future reference, one possible solution would be ssh with X forward. Here's an example of Dockerfile with X forward working: https://github.com/bmpvieira/Dockerfiles/tree/master/seqgrapher
